### ISSUE TITLE
Hi, I am unable to compile OpenWRT after accessing and enabling xTerminal in the make menuconfig

### ISSUE THREAD

**Issue by rajultandon** [zhaojh329/xterminal#1]
Hi, I am unable to compile OpenWRT after accessing and enabling xTerminal in make menu config.

/home/Pi/openwrt-chaoscalmer/openwrt/dl/gcc-linaro-4.8-2014.04.tar.xz: Compressed data is corrupt

How do I fix this?

**Comment by zhaojh329** [comment]
Please use the new rtty
